my_app_domain: my-app.dev.com
my_app_name: my-app
admin_user: web-admin
admin_password: "{{ vault_admin_password }}"
admin_group: administrators
ansible_ssh_private_key_file: ~/.ssh/web_id_rsa
ssh_public_key_file: "{{ ansible_ssh_private_key_file }}.pub"
