---
# This playbook will allow ssh connections and denied the rest

- name: Allow SSH connections
  become: yes
  ufw:
    rule: allow
    name: OpenSSH
  notify: restart sshd
  tags: firewall

- name: Deny all other incoming traffic by default
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  notify: restart sshd

- name: UFW Status
  become: yes
  shell: ufw status
  register: ufw_status
  tags: firewall

- name: Debug Result
  become: yes
  debug:
    var: ufw_status.stdout_lines
