---
# This playbook will install NGINX

- name: Install NGINX
  become: yes
  apt:
    name: nginx
    update_cache: yes
    state: present
  tags: nginx

- name: Delete default NGINX site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup NGINX conf
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
